config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'game/input'
  get 'game/output'
  root 'session#login'
  get 'session/login'
  get 'session/create'
  get 'session/logout'
  post 'session/create'
  get 'users/index'
  post 'users/new'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionHelper

  before_action :require_login

  around_action :switch_locale

  private

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def require_login
    unless signed_in?
      flash[:danger] = 'Требуется логин'
      redirect_to session_login_url
    end
  end
end

app/controllers/game_controller.rb
# frozen_string_literal: true

class GameController < ApplicationController
  def input; end

  def output; end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]

  def login; end

  def create
    user = User.find_by(username: params[:login])

    if user&.authenticate(params[:password])
      sign_in user
      redirect_to game_input_url
    else
      flash.now[:danger] = t(:wrong_login_or_password)
      redirect_to session_login_url
    end
  end

  def logout
    sign_out
    redirect_to session_login_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
#
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[new create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    render json: @users.to_json, status: 200
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to game_input_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/game_helper.rb
# frozen_string_literal: true

module GameHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 20.days, http_only: true }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/game/input.html.erb
    <%= stylesheet_link_tag 'game', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'game', 'data-turbolinks-track': 'reload' %>

<div id="g"></div>
	
<div class="logo">
  <p class="info"><%= I18n.t :сlick_the_P_to_get_started %></p>
  <div class="card left">
    <div class="flipper">
      <div class="f c1">F</div>
      <div class="b contentbox" id="stats">
        <div class="padded">
          <h2><%= t :figures %></h2>
          Looks like you haven't FLIPped yet.
          <a href="javascript:;" class="playnow"><%= t :play_now %></a>
        </div>
      </div>
    </div>
  </div>
  <div class="card active twist">
    <div class="flipper">
      <div class="b f">
        <div class="c2">L</div>
      </div>
    </div>
  </div>
  <div class="card left">
    <div class="flipper">
      <div class="f c3">I</div>
      <div class="b contentbox instructions">
        <div class="padded">
          <h2><%= t :unstructions %></h2>
          <p><%= t :press_p_to_pause_or_ESC_to_abandon_game %></p>
          <p><%= t :Flip_is_a_timed_card_memory_game__Click_the_green_cards_to_see %>
             <%= t :what_symbol_they_uncover_and_try_to_find_the_matching_symbol_underneath %>
             <%= t :the_other_cards %></p>
          <p><%= t :Uncover_two_matching_symbols_at_once_to_eliminate_them_from_the_game %></p>
          <p><%= t :Eliminate_all_cards_as_fast_as_you_can_to_win_the_game__Have_fun_FLIPing %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="flipper">
      <div class="f c4">P</div>
      <div class="b contentbox levels">
        <a href="javascript:;" data-level="8" class="play"><%= t :casual %></a>
        <a href="javascript:;" data-level="18" class="play"><%= t :medium %></a>
        <a href="javascript:;" data-level="32" class="play"><%= t :hard %></a>
      </div>
    </div>
  </div>

  <%= link_to I18n.t(:log_out), session_logout_path %>

</div>

app/views/game/output.html.erb
<h1>Player rating</h1>

<script>
    print (score);
</script>

<%= link_to 'New game', game_input_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/login.html.erb
<%= stylesheet_link_tag 'session', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1><%= t :authorization %></h1>

<div class="form">  
    <%= form_with url: session_create_url, method: :post, local: true do |f| %>
        <%= f.label t(:login) %>
        <%= f.text_field :login, required: true, label: t(:login) %>
        <%= f.label t(:password) %>
        <%= f.password_field :password, required: true, label: t(:password) %>
        <%= f.submit t(:log_in)%>
    <% end %>
</div>

<%= link_to I18n.t(:registration), new_user_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, t(:error)) %> <%= t :prohibited_this_user_from_being_saved %></h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t(:login) %>
    <%= form.text_field :username, required: true  %>
  </div>

  <div class="field">
    <%= form.label t(:password) %>
    <%= form.text_field :password, required: true  %>
  </div>

  <div class="field">
    <%= form.label t(:password_confirmation)%>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div class="actions">
    <%= form.submit t(:create_user)%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.score %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1><%= I18n.t :new_user %></h1>

<div class="form">  
    <%= render 'form', user: @user %>
</div>

<%= link_to t(:back), session_login_url %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag 'session', media: 'all', 'data-turbolinks-track': 'reload' %>

<form class="decor">
  <div class="form-left-decoration"></div>
  <div class="form-right-decoration"></div>
  <div class="circle"></div>

  <div class="form-inner">

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Score:</strong>
  <%= @user.score %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
  </div>
</form>